In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
 

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/homeprices.csv")
data

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
x=data.iloc[:,1].values
y=data.iloc[:,2].values

In [ ]:
x

array([2600, 3000, 3200, 3600, 4000, 2600, 2800, 3300, 3600, 2600, 2900,
       3100, 3600])

In [ ]:
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

In [ ]:
a=data.drop(["town"],axis=1)
a.columns

Index(['area', 'price'], dtype='object')

In [ ]:
y=a["price"]
x=a.drop(["price"],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
#from sklearn.preprocessing import StandardScaler
#sc=StandardScaler()
#x_train=sc.fit_transform(x_train)
#x_test=sc.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(random_state=0)
lr.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [ ]:
y_pred=lr.predict(x_test)
y_pred


array([575000, 565000, 710000, 575000])

In [ ]:
y_pred=lr.predict(x_train)
y_pred

array([650000, 710000, 565000, 710000, 575000, 710000, 575000, 575000,
       710000])

In [ ]:
m=[[3000]]

In [ ]:
print(m)

[[3000]]


In [ ]:
y_pred=lr.predict(m)
y_pred

array([710000])

In [ ]:
y_test

6     615000
11    620000
4     725000
10    600000
Name: price, dtype: int64

In [ ]:
y_train

2     610000
8     710000
1     565000
7     650000
9     575000
3     680000
0     550000
5     585000
12    695000
Name: price, dtype: int64

In [ ]:
x_test

array([[-0.7750576 ],
       [-0.05345225],
       [ 2.11136381],
       [-0.53452248]])

In [ ]:
x_train

array([[ 0.18708287],
       [ 1.14922334],
       [-0.29398737],
       [ 0.42761799],
       [-1.25612784],
       [ 1.14922334],
       [-1.25612784],
       [-1.25612784],
       [ 1.14922334]])