In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data_set=pd.read_csv("/content/drive/MyDrive/housepricedata_(1).csv")
data_set

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0                3             8           0         548                 1  
1                3             6           1         460                 1  
2                3             6           1         608                 1  
3                3             7           1         642                 0  
4                4             9           1         836                 1  
...            ...           ...         ...         ...               ...  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0  

[1460 rows x 11 columns]

In [ ]:
a=data_set.isnull().sum()

In [ ]:
y=data_set["AboveMedianPrice"]
x=data_set.drop(["AboveMedianPrice"],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=100)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=100)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
predictions=dtree.predict(x_test)
predictions

array([0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
rf_pred=dtree.predict(x_test)
rf_pred

array([0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,

In [ ]:
a=int(input("LotArea"))
b=int(input("OverallQual"))
c=int(input("OverallCond"))
d=int(input("TotalBsmtSF"))
e=int(input("FullBath"))
f=int(input("HalfBath"))
g=int(input("BedroomAbvGr"))
h=int(input("TotRmsAbvGrd"))
i=int(input("Fireplaces"))
j=int(input("GarageArea"))
data=pd.DataFrame({"LotArea":[a],
                "OverallQual":[b],
                "OverallCond":[c],
                "TotalBsmtSF":[d],
                "FullBath":[e],
                "HalfBath":[f],
                "BedroomAbvGr":[g],
                "TotRmsAbvGrd":[h],
                "FirePlaces":[i],
                "GarageArea":[j]})
data

LotArea856
OverallQual2
OverallCond45
TotalBsmtSF2
FullBath3
HalfBath2
BedroomAbvGr8
TotRmsAbvGrd6
Fireplaces5
GarageArea1


LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0      856            2           45            2         3         2   

   BedroomAbvGr  TotRmsAbvGrd  FirePlaces  GarageArea  
0             8             6           5           1

In [ ]:
y_pred=dtree.predict(data)
y_pred

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- FirePlaces
Feature names seen at fit time, yet now missing:
- Fireplaces

  warnings.warn(message, FutureWarning)


array([1])

In [ ]:
y_pred=rf.predict(data)
y_pred

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- FirePlaces
Feature names seen at fit time, yet now missing:
- Fireplaces

  warnings.warn(message, FutureWarning)


array([0])

In [ ]:
y_pred=rf.predict(data)
y_pred
if y_pred==1:
  print("above median price")
else:
  print("not above median price")

not above median price


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- FirePlaces
Feature names seen at fit time, yet now missing:
- Fireplaces

  warnings.warn(message, FutureWarning)


In [ ]:
y_pred=dtree.predict(data)
y_pred
if y_pred==1:
  print("above median price")
else:
  print("not above median price")

above median price


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- FirePlaces
Feature names seen at fit time, yet now missing:
- Fireplaces

  warnings.warn(message, FutureWarning)
