In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dset=pd.read_csv("/content/drive/MyDrive/breast-cancer_csv (1).csv")
dset

age menopause tumor-size inv-nodes node-caps  deg-malig breast  \
0    40-49   premeno      15-19       0-2       yes          3  right   
1    50-59      ge40      15-19       0-2        no          1  right   
2    50-59      ge40      35-39       0-2        no          2   left   
3    40-49   premeno      35-39       0-2       yes          3  right   
4    40-49   premeno      30-34       3-5       yes          2   left   
..     ...       ...        ...       ...       ...        ...    ...   
281  50-59      ge40      30-34       6-8       yes          2   left   
282  50-59   premeno      25-29       3-5       yes          2   left   
283  30-39   premeno      30-34       6-8       yes          2  right   
284  50-59   premeno      15-19       0-2        no          2  right   
285  50-59      ge40      40-44       0-2        no          3   left   

    breast-quad irradiat                 Class  
0       left_up       no     recurrence-events  
1       central       no  no-recurrence-events  
2      left_low       no     recurrence-events  
3      left_low      yes  no-recurrence-events  
4      right_up       no     recurrence-events  
..          ...      ...                   ...  
281    left_low       no  no-recurrence-events  
282    left_low      yes  no-recurrence-events  
283    right_up       no  no-recurrence-events  
284    left_low       no  no-recurrence-events  
285    right_up       no  no-recurrence-events  

[286 rows x 10 columns]

In [ ]:
a=dset.drop(["menopause","breast-quad"],axis=1)
a


age tumor-size inv-nodes node-caps  deg-malig breast irradiat  \
0    40-49      15-19       0-2       yes          3  right       no   
1    50-59      15-19       0-2        no          1  right       no   
2    50-59      35-39       0-2        no          2   left       no   
3    40-49      35-39       0-2       yes          3  right      yes   
4    40-49      30-34       3-5       yes          2   left       no   
..     ...        ...       ...       ...        ...    ...      ...   
281  50-59      30-34       6-8       yes          2   left       no   
282  50-59      25-29       3-5       yes          2   left      yes   
283  30-39      30-34       6-8       yes          2  right       no   
284  50-59      15-19       0-2        no          2  right       no   
285  50-59      40-44       0-2        no          3   left       no   

                    Class  
0       recurrence-events  
1    no-recurrence-events  
2       recurrence-events  
3    no-recurrence-events  
4       recurrence-events  
..                    ...  
281  no-recurrence-events  
282  no-recurrence-events  
283  no-recurrence-events  
284  no-recurrence-events  
285  no-recurrence-events  

[286 rows x 8 columns]

In [ ]:
b=a.drop(["node-caps"],axis=1)

In [ ]:
b["irradiat"]=[1 if each=="no" else 2 for each in b.irradiat]
b

age tumor-size inv-nodes  deg-malig breast  irradiat  \
0    40-49      15-19       0-2          3  right         1   
1    50-59      15-19       0-2          1  right         1   
2    50-59      35-39       0-2          2   left         1   
3    40-49      35-39       0-2          3  right         2   
4    40-49      30-34       3-5          2   left         1   
..     ...        ...       ...        ...    ...       ...   
281  50-59      30-34       6-8          2   left         1   
282  50-59      25-29       3-5          2   left         2   
283  30-39      30-34       6-8          2  right         1   
284  50-59      15-19       0-2          2  right         1   
285  50-59      40-44       0-2          3   left         1   

                    Class  
0       recurrence-events  
1    no-recurrence-events  
2       recurrence-events  
3    no-recurrence-events  
4       recurrence-events  
..                    ...  
281  no-recurrence-events  
282  no-recurrence-events  
283  no-recurrence-events  
284  no-recurrence-events  
285  no-recurrence-events  

[286 rows x 7 columns]

In [ ]:
b["breast"]=[0 if each=="right" else 1 for each in b.breast]
b

age tumor-size inv-nodes  deg-malig  breast  irradiat  \
0    40-49      15-19       0-2          3       0         1   
1    50-59      15-19       0-2          1       0         1   
2    50-59      35-39       0-2          2       1         1   
3    40-49      35-39       0-2          3       0         2   
4    40-49      30-34       3-5          2       1         1   
..     ...        ...       ...        ...     ...       ...   
281  50-59      30-34       6-8          2       1         1   
282  50-59      25-29       3-5          2       1         2   
283  30-39      30-34       6-8          2       0         1   
284  50-59      15-19       0-2          2       0         1   
285  50-59      40-44       0-2          3       1         1   

                    Class  
0       recurrence-events  
1    no-recurrence-events  
2       recurrence-events  
3    no-recurrence-events  
4       recurrence-events  
..                    ...  
281  no-recurrence-events  
282  no-recurrence-events  
283  no-recurrence-events  
284  no-recurrence-events  
285  no-recurrence-events  

[286 rows x 7 columns]

In [ ]:
b["Class"]=[0 if each=="no-recurrence-events" else 1 for each in b.Class]
b

age tumor-size inv-nodes  deg-malig  breast  irradiat  Class
0    40-49      15-19       0-2          3       0         1      1
1    50-59      15-19       0-2          1       0         1      0
2    50-59      35-39       0-2          2       1         1      1
3    40-49      35-39       0-2          3       0         2      0
4    40-49      30-34       3-5          2       1         1      1
..     ...        ...       ...        ...     ...       ...    ...
281  50-59      30-34       6-8          2       1         1      0
282  50-59      25-29       3-5          2       1         2      0
283  30-39      30-34       6-8          2       0         1      0
284  50-59      15-19       0-2          2       0         1      0
285  50-59      40-44       0-2          3       1         1      0

[286 rows x 7 columns]

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [ ]:
b["age"]=label_encoder.fit_transform(b["age"])
b["tumor-size"]=label_encoder.fit_transform(b["tumor-size"])
b["inv-nodes"]=label_encoder.fit_transform(b["inv-nodes"])

In [ ]:
b

age  tumor-size  inv-nodes  deg-malig  breast  irradiat  Class
0      2           2          0          3       0         1      1
1      3           2          0          1       0         1      0
2      3           6          0          2       1         1      1
3      2           6          0          3       0         2      0
4      2           5          4          2       1         1      1
..   ...         ...        ...        ...     ...       ...    ...
281    3           5          5          2       1         1      0
282    3           4          4          2       1         2      0
283    1           5          5          2       0         1      0
284    3           2          0          2       0         1      0
285    3           7          0          3       1         1      0

[286 rows x 7 columns]

In [ ]:
y=b["irradiat"]
x=b.drop(["irradiat"],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=100)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
rf_pred=dtree.predict(x_test)
rf_pred

array([1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train,y_train)


SVC()

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
rf_pred=rf.predict(x_test)
rf_pred

array([1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1])

In [ ]:
a=int(input("age"))
b=int(input("tumor_size"))
c=int(input("inv-nodes"))
d=int(input("deg-malig"))
e=int(input("breast"))
f=int(input("Class"))

a=pd.DataFrame({"age":[a],
                "tumor_size":[b],
                "inv-nodes":[c],
                "deg-malig":[d],
                "breast":[e],
                "Class":[f]})
                

age45
tumor_size3
inv-nodes2
deg-malig5
breast2
Class1


In [ ]:
a


age  tumor_size  inv-nodes  deg-malig  breast  Class
0   45           3          2          5       2      1

In [ ]:
rf_pred=dtree.predict(a)
rf_pred

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- tumor_size
Feature names seen at fit time, yet now missing:
- tumor-size

  warnings.warn(message, FutureWarning)


array([2])

In [ ]:
y_pred=model.predict(a)
y_pred

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- tumor_size
Feature names seen at fit time, yet now missing:
- tumor-size

  warnings.warn(message, FutureWarning)


array([1])

In [ ]:
y_pred=dtree.predict(a)
y_pred

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- tumor_size
Feature names seen at fit time, yet now missing:
- tumor-size

  warnings.warn(message, FutureWarning)


array([2])